WITH VALUE AS (
    SELECT HISTORY_ID, DAILY_FEE, CAR_TYPE,
           DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
         ELSE 'NONE' END AS PERIOD_TYPE
    FROM CAR_RENTAL_COMPANY_CAR 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
    WHERE CAR_TYPE = '트럭')
    
SELECT A.HISTORY_ID,
       ROUND(A.DAILY_FEE * A.PERIOD * 
        (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM VALUE AS A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B
     ON A.PERIOD_TYPE = B.DURATION_TYPE 
     AND A.CAR_TYPE = B.CAR_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC