WITH VALUE AS (
    SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
    FROM APPOINTMENT JOIN PATIENT USING(PT_NO)
    WHERE DATE(APNT_YMD) = '2022-04-13'
          AND MCDP_CD = 'CS'
          AND APNT_CNCL_YN = 'N'
    )
    
SELECT A.APNT_NO, A.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM VALUE AS A LEFT JOIN DOCTOR AS B ON A.MDDR_ID = B.DR_ID
ORDER BY A.APNT_YMD

-- SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
-- FROM APPOINTMENT AP 
-- JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
-- JOIN PATIENT P ON P.PT_NO = AP.PT_NO
-- WHERE AP.APNT_CNCL_YMD IS NULL AND AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '2022-04-13%'
-- ORDER BY AP.APNT_YMD